services:
  suricata:
    image: custom-suricata:1.0.1
    container_name: suricata
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - ./suricata.yaml:/usr/etc/suricata/suricata.yaml
      - ./eve-kafkatype.so:/usr/local/lib/eve-kafkatype.so
    #  - ./rules/youtube.rules:/usr/local/var/lib/suricata/rules/suricata.rules
    #  - ./logs:/var/log/suricata
    command: -i ${DEVICE_INTERFACE} -vvv
    # stdin_open: true  # -i
    # tty: true         # -t
    restart: unless-stopped
